### PR TITLE
update to v1.2.13

### PR DESCRIPTION
**Pull request by xaki23**
some fallout from https://github.com/QubesOS/qubes-issues/issues/7977

(as discussed on irc with @marmarek ...)

i ended up nuking all the patches. they were either...
* unrelated to qubes (the s390 / Z / power / rhel9 ones)
* already applied to 1.2.13 (the CVE, configure and crc32 ones)
* incomprehensible (the fixuncrypt one)

the changed .sha512 was verified from three different ASes over ~2 hours, but please crosscheck this one before merge.
confirmed to build for r4.1 target on a fc37 buildvm, not tested to actualy work, but not expecting any surprises there.
filing this against main/master, please propagate to release branches as needed.

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by xaki23** [comment]
looking at the CI logs ... @fepitre should really hang out on the usual irc/matrix places more. ;)

**Comment by marmarek** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]

**Pull request merged**
